### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by Rojan7435** [javatlacati/datastrructureskotlin#2]
Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.1.2-4:compile (compile) on project datastrructures: Compilation failure: Compilation failure:
C:\Users\rojan\Documents\NetBeansProjects\datastrructureskotlin\src\main\java\katlin\lists\singlelinkedlists\JosephusProblem.kt:[3,39] Unresolved reference: recursive
C:\Users\rojan\Documents\NetBeansProjects\datastrructureskotlin\src\main\java\katlin\lists\singlelinkedlists\JosephusProblem.kt:[10,28] Unresolved reference: Node
C:\Users\rojan\Documents\NetBeansProjects\datastrructureskotlin\src\main\java\katlin\lists\singlelinkedlists\JosephusProblem.kt:[12,24] Unresolved reference: Node
C:\Users\rojan\Documents\NetBeansProjects\datastrructureskotlin\src\main\java\katlin\lists\singlelinkedlists\JosephusProblem.kt:[15,33] Unresolved reference: Node

**Comment by javatlacati** [comment]
On netbeans??? https://blog.jetbrains.com/kotlin/2016/09/kotlin-netbeans-plugin-beta-is-out/

**Comment by javatlacati** [comment]
it can't find RecursiveNode from the kotlin package from the error, perhaps you need to install the plugin first to make it compile the kotlin to Java readable .class

**Comment by Nish-Hub** [comment]
Which jdk version are u using ?

**Comment by javatlacati** [comment]
I think he has jdk 1.8.145 and I'm still on 1.8.131

**Comment by Kayswift** [comment]
Same build failure. Kotlin plugin is already installed on my netbeans.

**Comment by javatlacati** [comment]
Please see commit 636ab28 still needs to be changed to another package but the compilation issue should be gone. Hopefully will change it at night if no one has already done it.
