### ISSUE TITLE
COMPILATION ERROR

### ISSUE THREAD

**Issue by Kayswift** [javatlacati/datastrructureskotlin#3]
cd C:\Users\USER\Documents\NetBeansProjects\new\datastrructureskotlin-master; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_141" cmd /c "\"\"C:\\Program Files\\NetBeans 8.2\\java\\maven\\bin\\mvn.bat\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.2\\java\\maven-nblib\\netbeans-eventspy.jar\" -Djava.net.useSystemProxies=true clean install\""
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building datastrructures 1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-clean-plugin:2.4.1:clean (default-clean) @ datastrructures ---
Deleting C:\Users\USER\Documents\NetBeansProjects\new\datastrructureskotlin-master\target

--- maven-resources-plugin:2.5:resources (default-resources) @ datastrructures ---
[debug] execute contextualize
Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
skip non existing resourceDirectory C:\Users\USER\Documents\NetBeansProjects\new\datastrructureskotlin-master\src\main\resources

--- maven-compiler-plugin:3.6.1:compile (default-compile) @ datastrructures ---
Changes detected - recompiling the module!
File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
Compiling 32 source files to C:\Users\USER\Documents\NetBeansProjects\new\datastrructureskotlin-master\target\classes
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
jaba/bags/ArrayBasedBag.java:[4,32] package sun.plugin.dom.exception does not exist
1 error
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 17.675s
Finished at: Thu Aug 24 06:42:44 WAT 2017
Final Memory: 11M/27M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project datastrructures: Compilation failure
jaba/bags/ArrayBasedBag.java:[4,32] package sun.plugin.dom.exception does not exist
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by javatlacati** [comment]
I'll change the NoModificationAllowedException to a custom exception thank you.

**Comment by Kayswift** [comment]
Okay
